### ISSUE TITLE
grid3_client error on QA net

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/farmerbot#8]
Attempting to run `farmerbot`  (rc11) on qanet, I see the following error:

```
$ docker compose up
[+] Running 4/0
 ⠿ Container qa-redis-1         Created                                         0.0s
 ⠿ Container qa-rmbpeer-1       Created                                         0.0s
 ⠿ Container qa-grid3_client-1  Created                                         0.0s
 ⠿ Container qa-farmerbot-1     Created                                         0.0s
Attaching to qa-farmerbot-1, qa-grid3_client-1, qa-redis-1, qa-rmbpeer-1
qa-redis-1         | 1:C 16 Mar 2023 19:42:20.940 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
qa-redis-1         | 1:C 16 Mar 2023 19:42:20.940 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
qa-redis-1         | 1:C 16 Mar 2023 19:42:20.940 # Configuration loaded
qa-redis-1         | 1:M 16 Mar 2023 19:42:20.940 * monotonic clock: POSIX clock_gettime
qa-redis-1         | 1:M 16 Mar 2023 19:42:20.941 * Running mode=standalone, port=6379.
qa-redis-1         | 1:M 16 Mar 2023 19:42:20.941 # Server initialized
qa-redis-1         | 1:M 16 Mar 2023 19:42:20.941 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
qa-redis-1         | 1:M 16 Mar 2023 19:42:20.941 * Loading RDB produced by version 7.0.8
qa-redis-1         | 1:M 16 Mar 2023 19:42:20.941 * RDB age 48 seconds
qa-redis-1         | 1:M 16 Mar 2023 19:42:20.941 * RDB memory usage when created 1.06 Mb
qa-redis-1         | 1:M 16 Mar 2023 19:42:20.941 * Done loading RDB, keys loaded: 2, keys expired: 2.
qa-redis-1         | 1:M 16 Mar 2023 19:42:20.941 * DB loaded from disk: 0.000 seconds
qa-redis-1         | 1:M 16 Mar 2023 19:42:20.941 * Ready to accept connections
qa-grid3_client-1  | yarn run v1.22.19
qa-rmbpeer-1       | 2023-03-16T19:42:23.258Z DEBUG [rustls::client::hs] No cached session for DnsName(DnsName(DnsName("tfchain.qa.grid.tf")))
qa-rmbpeer-1       | 2023-03-16T19:42:23.258Z DEBUG [rustls::client::hs] Not resuming any session
qa-grid3_client-1  | warning package.json: No license field
qa-grid3_client-1  | $ /node_modules/.bin/httpserver -c /root/config.json
qa-rmbpeer-1       | 2023-03-16T19:42:23.436Z DEBUG [rustls::client::hs] Using ciphersuite TLS13_AES_256_GCM_SHA384
qa-rmbpeer-1       | 2023-03-16T19:42:23.436Z DEBUG [rustls::client::tls13] Not resuming
qa-rmbpeer-1       | 2023-03-16T19:42:23.436Z DEBUG [rustls::client::tls13] TLS1.3 encrypted extensions: [ServerNameAck]
qa-rmbpeer-1       | 2023-03-16T19:42:23.436Z DEBUG [rustls::client::hs] ALPN protocol is None
qa-rmbpeer-1       | 2023-03-16T19:42:23.604Z DEBUG [rustls::client::tls13] Ticket saved
qa-rmbpeer-1       | 2023-03-16T19:42:23.604Z DEBUG [rustls::client::tls13] Ticket saved
qa-rmbpeer-1       | 2023-03-16T19:42:24.657Z DEBUG [rmb_peer] twin relay domain: Some("relay.qa.grid.tf")
qa-rmbpeer-1       | 2023-03-16T19:42:24.657Z INFO  [rmb_peer] twin: 251
qa-rmbpeer-1       | 2023-03-16T19:42:25.437Z DEBUG [tungstenite::handshake::client] Client handshake done.
qa-grid3_client-1  | 2023-03-16 19:42:26        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
qa-grid3_client-1  | 2023-03-16 19:42:26        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
qa-grid3_client-1  | Key with address: 5HW86mnxp4JBpQrASKbHcJPf2Mxmma8CuiB5azZZJq32a38c is loaded.
qa-grid3_client-1  | Executing method: getTwinIdByAccountId with args: 5HW86mnxp4JBpQrASKbHcJPf2Mxmma8CuiB5azZZJq32a38c
qa-grid3_client-1  | The server is running on port 3000
qa-grid3_client-1  | Executing Method: get_my_twin_id in Module: twins with Payload: [object Object]
qa-grid3_client-1  | Validation succeed
qa-grid3_client-1  | Executing method: getTwinIdByAccountId with args: 5HW86mnxp4JBpQrASKbHcJPf2Mxmma8CuiB5azZZJq32a38c
qa-grid3_client-1  | Executing Method: activeRentContractForNode in Module: contracts with Payload: [object Object]
qa-grid3_client-1  | Validation succeed
qa-grid3_client-1  | Executing method: activeRentContractForNode with args: 8
qa-grid3_client-1  | Executing Method: activeRentContractForNode in Module: contracts with Payload: [object Object]
qa-grid3_client-1  | Validation succeed
qa-grid3_client-1  | Executing method: activeRentContractForNode with args: 11
qa-grid3_client-1  | Executing Method: setNodePower in Module: nodes with Payload: [object Object]
qa-grid3_client-1  | Validation succeed
qa-grid3_client-1  | Executing method: getBalanceOf with args: 5HW86mnxp4JBpQrASKbHcJPf2Mxmma8CuiB5azZZJq32a38c
qa-grid3_client-1  | node:internal/errors:490
qa-grid3_client-1  |     ErrorCaptureStackTrace(err);
qa-grid3_client-1  |     ^
qa-grid3_client-1  | 
qa-grid3_client-1  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
qa-grid3_client-1  |     at new NodeError (node:internal/errors:399:5)
qa-grid3_client-1  |     at ServerResponse.setHeader (node:_http_outgoing:663:11)
qa-grid3_client-1  |     at ServerResponse.header (/node_modules/express/lib/response.js:794:10)
qa-grid3_client-1  |     at ServerResponse.send (/node_modules/express/lib/response.js:174:12)
qa-grid3_client-1  |     at ServerResponse.json (/node_modules/express/lib/response.js:278:15)
qa-grid3_client-1  |     at ServerResponse.send (/node_modules/express/lib/response.js:162:21)
qa-grid3_client-1  |     at /node_modules/grid3_client/dist/node/server/http_server.js:55:29
qa-grid3_client-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
qa-grid3_client-1  |   code: 'ERR_HTTP_HEADERS_SENT'
qa-grid3_client-1  | }
qa-grid3_client-1  | 
qa-grid3_client-1  | Node.js v18.14.2
qa-grid3_client-1  | error Command failed with exit code 1.
qa-grid3_client-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
qa-grid3_client-1 exited with code 1
```

**Comment by brandonpille** [comment]
That is a grid3 client error. Can you create it in https://github.com/threefoldtech/grid3_client_ts?

**Comment by brandonpille** [comment]
Could you also provide me the farmerbot.log file? From the config folder.

**Comment by scottyeager** [comment]
I didn't have the original log file. Since I'd moved the nodes over to devnet for further testing, this example is a bit different, but produces the same error. I actually deleted the nodes from QA net altogether, so these node ids don't exist anymore. If needed, I can move the nodes back and try to recreate the original error.

I'll open the issue on the grid3_client_ts repo too. 

Docker compose console logs:

```
Attaching to qa-farmerbot-1, qa-grid3_client-1, qa-redis-1, qa-rmbpeer-1
qa-redis-1         | 1:C 17 Mar 2023 21:45:24.034 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
qa-redis-1         | 1:C 17 Mar 2023 21:45:24.034 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
qa-redis-1         | 1:C 17 Mar 2023 21:45:24.034 # Configuration loaded
qa-redis-1         | 1:M 17 Mar 2023 21:45:24.035 * monotonic clock: POSIX clock_gettime
qa-redis-1         | 1:M 17 Mar 2023 21:45:24.035 * Running mode=standalone, port=6379.
qa-redis-1         | 1:M 17 Mar 2023 21:45:24.035 # Server initialized
qa-redis-1         | 1:M 17 Mar 2023 21:45:24.036 * Loading RDB produced by version 7.0.8
qa-redis-1         | 1:M 17 Mar 2023 21:45:24.036 * RDB age 7645 seconds
qa-redis-1         | 1:M 17 Mar 2023 21:45:24.036 * RDB memory usage when created 1.06 Mb
qa-redis-1         | 1:M 17 Mar 2023 21:45:24.036 * Done loading RDB, keys loaded: 2, keys expired: 0.
qa-redis-1         | 1:M 17 Mar 2023 21:45:24.036 * DB loaded from disk: 0.000 seconds
qa-redis-1         | 1:M 17 Mar 2023 21:45:24.036 * Ready to accept connections
qa-grid3_client-1  | yarn run v1.22.19
qa-grid3_client-1  | warning package.json: No license field
qa-grid3_client-1  | $ /node_modules/.bin/httpserver -c /root/config.json
qa-rmbpeer-1       | 2023-03-17T21:45:26.305Z DEBUG [rustls::client::hs] No cached session for DnsName(DnsName(DnsName("tfchain.qa.grid.tf")))
qa-rmbpeer-1       | 2023-03-17T21:45:26.305Z DEBUG [rustls::client::hs] Not resuming any session
qa-rmbpeer-1       | 2023-03-17T21:45:26.493Z DEBUG [rustls::client::hs] Using ciphersuite TLS13_AES_256_GCM_SHA384
qa-rmbpeer-1       | 2023-03-17T21:45:26.493Z DEBUG [rustls::client::tls13] Not resuming
qa-rmbpeer-1       | 2023-03-17T21:45:26.493Z DEBUG [rustls::client::tls13] TLS1.3 encrypted extensions: [ServerNameAck]
qa-rmbpeer-1       | 2023-03-17T21:45:26.493Z DEBUG [rustls::client::hs] ALPN protocol is None
qa-rmbpeer-1       | 2023-03-17T21:45:26.717Z DEBUG [rustls::client::tls13] Ticket saved
qa-rmbpeer-1       | 2023-03-17T21:45:26.717Z DEBUG [rustls::client::tls13] Ticket saved
qa-rmbpeer-1       | 2023-03-17T21:45:27.976Z DEBUG [rmb_peer] twin relay domain: Some("relay.qa.grid.tf")
qa-rmbpeer-1       | 2023-03-17T21:45:27.976Z INFO  [rmb_peer] twin: 251
qa-rmbpeer-1       | 2023-03-17T21:45:28.736Z DEBUG [tungstenite::handshake::client] Client handshake done.
qa-grid3_client-1  | 2023-03-17 21:45:29        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
qa-grid3_client-1  | 2023-03-17 21:45:29        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
qa-grid3_client-1  | Key with address: 5HW86mnxp4JBpQrASKbHcJPf2Mxmma8CuiB5azZZJq32a38c is loaded.
qa-grid3_client-1  | Executing method: getTwinIdByAccountId with args: 5HW86mnxp4JBpQrASKbHcJPf2Mxmma8CuiB5azZZJq32a38c
qa-grid3_client-1  | The server is running on port 3000
qa-grid3_client-1  | Executing Method: get_my_twin_id in Module: twins with Payload: [object Object]
qa-grid3_client-1  | Validation succeed
qa-grid3_client-1  | Executing method: getTwinIdByAccountId with args: 5HW86mnxp4JBpQrASKbHcJPf2Mxmma8CuiB5azZZJq32a38c
qa-redis-1         | 1:M 17 Mar 2023 21:45:45.073 * 1 changes in 20 seconds. Saving...
qa-redis-1         | 1:M 17 Mar 2023 21:45:45.074 * Background saving started by pid 123
qa-redis-1         | 123:C 17 Mar 2023 21:45:45.088 * DB saved on disk
qa-redis-1         | 123:C 17 Mar 2023 21:45:45.089 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
qa-redis-1         | 1:M 17 Mar 2023 21:45:45.175 * Background saving terminated with success
qa-grid3_client-1  | Executing Method: get_my_twin_id in Module: twins with Payload: [object Object]
qa-grid3_client-1  | Validation succeed
qa-grid3_client-1  | Executing method: getTwinIdByAccountId with args: 5HW86mnxp4JBpQrASKbHcJPf2Mxmma8CuiB5azZZJq32a38c
qa-grid3_client-1  | Executing Method: setNodePower in Module: nodes with Payload: [object Object]
qa-grid3_client-1  | Validation succeed
qa-grid3_client-1  | Executing method: getBalanceOf with args: 5HW86mnxp4JBpQrASKbHcJPf2Mxmma8CuiB5azZZJq32a38c
qa-grid3_client-1  | Lock acquired
qa-grid3_client-1  | 2023-03-17 21:45:54        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
qa-grid3_client-1  | Executing Method: get_my_twin_id in Module: twins with Payload: [object Object]
qa-grid3_client-1  | Validation succeed
qa-grid3_client-1  | Executing method: getTwinIdByAccountId with args: 5HW86mnxp4JBpQrASKbHcJPf2Mxmma8CuiB5azZZJq32a38c
qa-redis-1         | 1:M 17 Mar 2023 21:46:06.068 * 1 changes in 20 seconds. Saving...
qa-redis-1         | 1:M 17 Mar 2023 21:46:06.069 * Background saving started by pid 231
qa-redis-1         | 231:C 17 Mar 2023 21:46:06.082 * DB saved on disk
qa-redis-1         | 231:C 17 Mar 2023 21:46:06.084 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
qa-redis-1         | 1:M 17 Mar 2023 21:46:06.171 * Background saving terminated with success
qa-grid3_client-1  | 2023-03-17 21:46:06        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
qa-grid3_client-1  | phase: {"applyExtrinsic":1}, section: balances, method: Withdraw
qa-grid3_client-1  | phase: {"applyExtrinsic":1}, section: balances, method: Deposit
qa-grid3_client-1  | phase: {"applyExtrinsic":1}, section: transactionPayment, method: TransactionFeePaid
qa-grid3_client-1  | phase: {"applyExtrinsic":1}, section: system, method: ExtrinsicFailed
qa-grid3_client-1  | Lock released
qa-grid3_client-1  | node:internal/errors:490
qa-grid3_client-1  |     ErrorCaptureStackTrace(err);
qa-grid3_client-1  |     ^
qa-grid3_client-1  | 
qa-grid3_client-1  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
qa-grid3_client-1  |     at new NodeError (node:internal/errors:399:5)
qa-grid3_client-1  |     at ServerResponse.setHeader (node:_http_outgoing:663:11)
qa-grid3_client-1  |     at ServerResponse.header (/node_modules/express/lib/response.js:794:10)
qa-grid3_client-1  |     at ServerResponse.send (/node_modules/express/lib/response.js:174:12)
qa-grid3_client-1  |     at ServerResponse.json (/node_modules/express/lib/response.js:278:15)
qa-grid3_client-1  |     at ServerResponse.send (/node_modules/express/lib/response.js:162:21)
qa-grid3_client-1  |     at /node_modules/grid3_client/dist/node/server/http_server.js:55:29 {
qa-grid3_client-1  |   code: 'ERR_HTTP_HEADERS_SENT'
qa-grid3_client-1  | }
qa-grid3_client-1  | 
qa-grid3_client-1  | Node.js v18.14.2
qa-grid3_client-1  | error Command failed with exit code 1.
qa-grid3_client-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

farmerbot.log:

```
2023-03-17 21:45:37 [INFO ] Initializing managers
2023-03-17 21:45:37 [INFO ] Initializing database
2023-03-17 21:45:37 [INFO ] [NODEMANAGER] Executing action: DATA_SET
2023-03-17 21:45:37 [DEBUG] [NODEMANAGER] ACTION: farmerbot.nodemanager.define
params.Params{
    params: [params.Param{
        key: 'id'
        value: '8'
    }, params.Param{
        key: 'twinid'
        value: '253'
    }, params.Param{
        key: 'never_shutdown'
        value: 'true'
    }]
    args: []
}
2023-03-17 21:45:37 [INFO ] [NODEMANAGER] Executing action: DATA_SET
2023-03-17 21:45:37 [DEBUG] [NODEMANAGER] ACTION: farmerbot.nodemanager.define
params.Params{
    params: [params.Param{
        key: 'id'
        value: '11'
    }, params.Param{
        key: 'twinid'
        value: '257'
    }, params.Param{
        key: 'never_shutdown'
        value: 'true'
    }]
    args: []
}
2023-03-17 21:45:37 [INFO ] [FARMMANAGER] Executing action: DATA_SET
2023-03-17 21:45:37 [DEBUG] [FARMMANAGER] ACTION: farmerbot.farmmanager.define
params.Params{
    params: [params.Param{
        key: 'id'
        value: '157'
    }, params.Param{
        key: 'public_ips'
        value: '0'
    }]
    args: []
}
2023-03-17 21:45:37 [DEBUG] {8: system.Node{
    id: 8
    twinid: 253
    farmid: 0
    description: ''
    certified: false
    dedicated: false
    public_config: false
    public_ips_used: 0
    resources: system.ConsumableResources{
        overprovision_cpu: 1.0
        total: system.Capacity{
            cru: 0
            sru: 0
            mru: 0
            hru: 0
        }
        used: system.Capacity{
            cru: 0
            sru: 0
            mru: 0
            hru: 0
        }
        system: system.Capacity{
            cru: 0
            sru: 0
            mru: 0
            hru: 0
        }
    }
    pools: []
    has_active_rent_contract: false
    powerstate: on
    timeout_claimed_resources: 0000-00-00 00:00:00
    last_time_powerstate_changed: 0000-00-00 00:00:00
    last_time_awake: 0000-00-00 00:00:00
    never_shutdown: true
}, 11: system.Node{
    id: 11
    twinid: 257
    farmid: 0
    description: ''
    certified: false
    dedicated: false
    public_config: false
    public_ips_used: 0
    resources: system.ConsumableResources{
        overprovision_cpu: 1.0
        total: system.Capacity{
            cru: 0
            sru: 0
            mru: 0
            hru: 0
        }
        used: system.Capacity{
            cru: 0
            sru: 0
            mru: 0
            hru: 0
        }
        system: system.Capacity{
            cru: 0
            sru: 0
            mru: 0
            hru: 0
        }
    }
    pools: []
    has_active_rent_contract: false
    powerstate: on
    timeout_claimed_resources: 0000-00-00 00:00:00
    last_time_powerstate_changed: 0000-00-00 00:00:00
    last_time_awake: 0000-00-00 00:00:00
    never_shutdown: true
}}
2023-03-17 21:45:37 [INFO ] Farmerbot up and running (version: 0.1.0-rc12)
2023-03-17 21:45:37 [INFO ] Processor is running
2023-03-17 21:45:42 [ERROR] [DATAMANAGER] Node 8 is not responding while we expect it to: timeout on blpop
2023-03-17 21:45:47 [ERROR] [DATAMANAGER] Node 11 is not responding while we expect it to: timeout on blpop
2023-03-17 21:45:47 [INFO ] [POWERMANAGER] Periodic wakeup for node 8
2023-03-17 21:45:47 [DEBUG] Received job 472d8eed-a7a2-4562-803b-9b021d999f0a
2023-03-17 21:45:47 [DEBUG] Assigned job 472d8eed-a7a2-4562-803b-9b021d999f0a to jobs.actors.farmerbot.powermanager:
2023-03-17 21:45:47 [DEBUG] jobs.ActionJob{
    guid: '472d8eed-a7a2-4562-803b-9b021d999f0a'
    twinid: 0
    action: 'farmerbot.powermanager.poweron'
    args: params.Params{
        params: [params.Param{
            key: 'nodeid'
            value: '8'
        }]
        args: []
    }
    result: params.Params{
        params: []
        args: []
    }
    state: tostart
    start: 2023-03-17 21:45:47
    end: 1970-01-01 00:00:00
    grace_period: 0
    error: ''
    timeout: 0
    src_twinid: 0
    src_action: ''
    dependencies: []
}

2023-03-17 21:45:47 [INFO ] [POWERMA
```

**Comment by brandonpille** [comment]
Ok so from the logs I can see it is setting the power target for node 8 and it uses the grid3 client for that. From the docker compose logs you can clearly see the grid3 client is crashing.

**Comment by brandonpille** [comment]
Issue was in grid3 client. Not the farmerbot
